# Generated by Django 4.2.1 on 2023-06-19 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('w', 'employee benefits'), ('b', 'purchase and repair of tools'), ('t', 'transport costs')], max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('summa', models.PositiveIntegerField()),
                ('date', models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 19, 416804)))),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('start_date', models.DateField(null=True, verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 19, 412808)))),
                ('end_date', models.DateField(null=True, verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 19, 413805)))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 19, 415805)))),
                ('time_work', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataoutput.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataoutput.user')),
            ],
        ),
        migrations.CreateModel(
            name='Smeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField()),
                ('date', models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 19, 413805)))),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataoutput.project')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataoutput.project')),
            ],
        ),
    ]
