# Generated by Django 4.2.1 on 2023-08-10 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataoutput', '0021_alter_expenses_category_alter_expenses_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smeta',
            options={'verbose_name_plural': 'Доходы'},
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2023, 8, 10, 10, 16, 19, 973260), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(auto_created=datetime.datetime(2023, 8, 10, 10, 16, 19, 969262), null=True, verbose_name='Дата завершения проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_created=datetime.datetime(2023, 8, 10, 10, 16, 19, 969262), null=True, verbose_name='Дата начала проекта'),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2023, 8, 10, 10, 16, 19, 970266), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2023, 8, 10, 10, 16, 19, 972258), verbose_name='Дата'),
        ),
    ]
