# Generated by Django 4.2.1 on 2023-06-19 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataoutput', '19_06_2023_0002_alter_expenses_date_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 22, 0, 54, 439525))),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='summa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True, verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 22, 0, 54, 439525))),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True, verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 22, 0, 54, 439525))),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='date',
            field=models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 22, 0, 54, 439525))),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='date',
            field=models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 22, 0, 54, 439525))),
        ),
    ]
