# Generated by Django 4.2.1 on 2023-06-19 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataoutput', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 29, 128611))),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True, verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 29, 125614))),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True, verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 29, 124617))),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='date',
            field=models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 29, 125614))),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='date',
            field=models.DateField(verbose_name=models.DateField(auto_created=datetime.datetime(2023, 6, 19, 21, 40, 29, 127610))),
        ),
    ]
