# Generated by Django 4.2.1 on 2023-06-20 18:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataoutput', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'Директора'},
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='smeta',
            options={'verbose_name_plural': 'Сметы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='userworktime',
            options={'verbose_name_plural': 'Время работы'},
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='director',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataoutput.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('w', 'employee benefits'), ('b', 'purchase and repair of tools'), ('t', 'transport costs')], max_length=1, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2023, 6, 20, 21, 38, 32, 401763), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='summa',
            field=models.FloatField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='project',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(auto_created=datetime.datetime(2023, 6, 20, 21, 38, 32, 398766), null=True, verbose_name='Дата завершения проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_created=datetime.datetime(2023, 6, 20, 21, 38, 32, 397773), null=True, verbose_name='Дата начала проекта'),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2023, 6, 20, 21, 38, 32, 398766), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dataoutput.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='summa',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='date',
            field=models.DateField(auto_created=datetime.datetime(2023, 6, 20, 21, 38, 32, 400764), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataoutput.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='time_work',
            field=models.PositiveIntegerField(verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='userworktime',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataoutput.user', verbose_name='Работник'),
        ),
    ]
